baseurl: "/northendlab-jekyll/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

title: Northendlab Jekyll | Personal Blog Template
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

#################### Comment Section (Disqus) ################
disqus_shortname: "" # Add your shortname for Disqus Comment. For example : mr-brown

# Scss Directory
sass:
  sass_dir: assets/scss
  style: compressed
  
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 6
paginate_path: "/page/:num"

# include
include:
  - _pages
  - _authors

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

  - scope:
      path: '_authors'
    values:
      permalink: /author/:basename:output_ext
      layout: author

  - scope:
      path: ''
      type: "posts"
    values:
      permalink: post/:title:output_ext
      layout: post

# Tags
tag_page_dir:         tag
tag_page_layout:      tags
tag_permalink_style:  pretty


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor